@startuml

autonumber

MainClass -> InputThread: 启动输入线程
MainClass -> PassengerQueue: 构建乘客队列
MainClass -> Elevator: 启动电梯线程
InputThread -> PassengerQueue: 放入乘客
PassengerQueue -> Elevator: 取出乘客
Elevator -> Elevator: 执行运行
InputThread -> PassengerQueue: 输入结束
PassengerQueue-> Elevator: 传递结束信号
Elevator -> Elevator: 电梯结束运行

@enduml